"""Generate PDF files for LeetCode problems."""

import re
from pathlib import Path

import markdown
from jinja2 import Environment, FileSystemLoader
from pypdf import PdfWriter
from pygments import highlight
from pygments.lexers import PythonLexer, get_lexer_by_name
from pygments.formatters import HtmlFormatter
from weasyprint import HTML

from .models import Problem


def get_template_dir() -> Path:
    """Get the templates directory path."""
    # Templates are in the project root templates/ directory
    return Path(__file__).parent.parent.parent / "templates"


def highlight_code_blocks(html_content: str) -> str:
    """
    Find code blocks in HTML and apply syntax highlighting.

    Looks for <pre><code>...</code></pre> patterns and highlights them.
    """
    # Pattern to match code blocks with optional language class
    pattern = r'<pre><code(?:\s+class="language-(\w+)")?>(.*?)</code></pre>'

    def replace_code(match):
        lang = match.group(1) or "python"  # Default to Python
        code = match.group(2)

        # Unescape HTML entities
        code = code.replace("&lt;", "<")
        code = code.replace("&gt;", ">")
        code = code.replace("&amp;", "&")
        code = code.replace("&quot;", '"')

        try:
            lexer = get_lexer_by_name(lang)
        except Exception:
            lexer = PythonLexer()

        formatter = HtmlFormatter(nowrap=True)
        highlighted = highlight(code, lexer, formatter)
        return f'<pre class="highlight"><code>{highlighted}</code></pre>'

    return re.sub(pattern, replace_code, html_content, flags=re.DOTALL)


def markdown_to_html(md_content: str) -> str:
    """Convert markdown to HTML with syntax highlighting."""
    # Convert markdown to HTML
    md = markdown.Markdown(
        extensions=["fenced_code", "tables", "codehilite"],
        extension_configs={
            "codehilite": {
                "css_class": "highlight",
                "guess_lang": False,
            }
        },
    )
    html = md.convert(md_content)

    # Apply additional syntax highlighting if needed
    html = highlight_code_blocks(html)

    return html


def extract_solution_body(md_content: str) -> str:
    """
    Extract the main content from a solution markdown file.

    Removes the header metadata (title, generated by, date, source, ---).
    """
    lines = md_content.split("\n")
    in_header = True
    separator_count = 0
    body_lines = []

    for line in lines:
        if in_header:
            if line.strip() == "---":
                separator_count += 1
                if separator_count >= 1:
                    in_header = False
            continue
        body_lines.append(line)

    return "\n".join(body_lines).strip()


def extract_problem_body(md_content: str) -> str:
    """
    Extract the main content from a problem markdown file.

    Removes the header metadata (title, difficulty, acceptance, source, ---).
    """
    lines = md_content.split("\n")
    in_header = True
    body_lines = []

    for line in lines:
        if in_header:
            if line.strip() == "---":
                in_header = False
            continue
        body_lines.append(line)

    return "\n".join(body_lines).strip()


def generate_problem_pdf(
    problem: Problem,
    problems_dir: Path,
    templates_dir: Path | None = None,
    force: bool = False,
) -> Path | None:
    """
    Generate a PDF for a single problem.

    Args:
        problem: Problem metadata
        problems_dir: Directory containing problem folders
        templates_dir: Directory containing HTML templates (default: project templates/)
        force: Force regeneration even if PDF is current

    Returns:
        Path to the generated PDF, or None if skipped
    """
    problem_dir = problem.get_problem_dir(problems_dir)
    problem_file = problem_dir / "problem.md"
    pdf_file = problem_dir / "solutions.pdf"

    # Check if problem exists
    if not problem_file.exists():
        print(f"  Skipping {problem.number}. {problem.title} (no problem.md)")
        return None

    # Find solution files
    claude_solution_file = problem_dir / "solution-claude-opus.md"
    gpt_solution_file = problem_dir / "solution-gpt5.md"

    # Check if we should skip
    if not force and pdf_file.exists():
        # Check if PDF is newer than all source files
        pdf_mtime = pdf_file.stat().st_mtime
        source_files = [problem_file]
        if claude_solution_file.exists():
            source_files.append(claude_solution_file)
        if gpt_solution_file.exists():
            source_files.append(gpt_solution_file)

        if all(f.stat().st_mtime < pdf_mtime for f in source_files):
            print(f"  Skipping {problem.number}. {problem.title} (PDF is current)")
            return None

    print(f"  Generating PDF for {problem.number}. {problem.title}...")

    # Load templates
    if templates_dir is None:
        templates_dir = get_template_dir()

    env = Environment(loader=FileSystemLoader(templates_dir))
    template = env.get_template("problem.html")

    # Read and convert problem content
    problem_md = problem_file.read_text(encoding="utf-8")
    problem_body = extract_problem_body(problem_md)
    problem_html = markdown_to_html(problem_body)

    # Read and convert Claude solution
    if claude_solution_file.exists():
        claude_md = claude_solution_file.read_text(encoding="utf-8")
        claude_body = extract_solution_body(claude_md)
        claude_html = markdown_to_html(claude_body)
    else:
        claude_html = "<p><em>Solution not available</em></p>"

    # Read and convert GPT-5 solution
    if gpt_solution_file.exists():
        gpt_md = gpt_solution_file.read_text(encoding="utf-8")
        gpt_body = extract_solution_body(gpt_md)
        gpt_html = markdown_to_html(gpt_body)
    else:
        gpt_html = "<p><em>Solution not available</em></p>"

    # Render the template
    html_content = template.render(
        number=problem.number,
        title=problem.title,
        difficulty=problem.difficulty,
        acceptance=problem.acceptance,
        url=problem.url,
        problem_content=problem_html,
        claude_solution=claude_html,
        gpt_solution=gpt_html,
    )

    # Generate PDF
    HTML(string=html_content).write_pdf(pdf_file)

    print(f"  Saved to {pdf_file}")
    return pdf_file


def concatenate_pdfs(pdf_paths: list[Path], output_path: Path) -> Path:
    """
    Concatenate multiple PDFs into a single file.

    Args:
        pdf_paths: List of PDF file paths to concatenate
        output_path: Path for the combined PDF

    Returns:
        Path to the combined PDF
    """
    writer = PdfWriter()

    for pdf_path in pdf_paths:
        if pdf_path.exists():
            writer.append(str(pdf_path))

    writer.write(str(output_path))
    writer.close()

    return output_path


def generate_all_pdfs(
    problems: list[Problem],
    problems_dir: Path,
    problemset_name: str,
    templates_dir: Path | None = None,
    force: bool = False,
) -> list[Path]:
    """
    Generate PDFs for all problems and concatenate into a combined file.

    Args:
        problems: List of problems from CSV
        problems_dir: Directory containing problem folders
        problemset_name: Name for the combined PDF (e.g., "grind75")
        templates_dir: Directory containing HTML templates
        force: Force regeneration even if PDFs are current

    Returns:
        List of paths to generated PDFs
    """
    generated = []
    all_pdfs = []
    total = len(problems)

    print(f"Generating PDFs for {total} problems...")

    for i, problem in enumerate(problems, 1):
        print(f"[{i}/{total}]", end="")
        try:
            pdf_path = generate_problem_pdf(
                problem, problems_dir, templates_dir, force
            )
            if pdf_path:
                generated.append(pdf_path)
            # Also track existing PDFs for concatenation
            problem_dir = problem.get_problem_dir(problems_dir)
            existing_pdf = problem_dir / "solutions.pdf"
            if existing_pdf.exists():
                all_pdfs.append(existing_pdf)
        except Exception as e:
            print(f"  ERROR: Failed to generate PDF for {problem.number}: {e}")

    print(f"\nGenerated {len(generated)}/{total} PDFs")

    # Concatenate all PDFs into a single file
    if all_pdfs:
        combined_pdf = Path(f"{problemset_name}-solutions.pdf")
        print(f"Concatenating {len(all_pdfs)} PDFs into {combined_pdf}...")
        concatenate_pdfs(all_pdfs, combined_pdf)
        print(f"Created {combined_pdf}")

    return generated
